cloudera/impyla

- impala/_rpc/hiveserver2.py
- impala/dbapi/hiveserver2.py
- impala/tests/test_dbapi_compliance.py
Not being a Thrift expert, there might be a less hackish way to get at the precision/scale values in the RPC request.
> Add decimal precision and scale to HS2 cursor description

- impala/bdf.py
- impala/context.py
- impala/tests/conftest.py
- impala/tests/test_bdf.py
- impala/udf/__init__.py
Added utility method to ImpalaContext to get the webdfs client.
Added a store_managed method to a BigDataFrame.  Previously it was not possibly to use store to create a managed table from a big dataframe, since path was a required argument.
> ImpalaContext and BigDataFrame cleanups

- impala/dbapi/hiveserver2.py
It appears we forgot to pass any per-query config options to the underlying RPC request.
Fixes #61.
> [IMPYLA-61] cursor.execute now passes configuation options

- impala/dbapi/interface.py
- impala/tests/test_dbapi_query_parameters.py
Even though PEP 249 only requires cursor.execute() to support one parameter style (the one specified in the module's paramstyle value, in this case pyformat), I think it would be nice to also support some of the others, similar to what the sqlite3 module does.
This branchs adds support for named style (first commit), question mark style and numeric style (second commit). The third commit adds some exception for commonly used errors (though I left the pyformat replacement as it is, e.g. it would raise a KeyError for a nonexistent parameter, as it already did). Final commit is a slight documentation addition to the specialized tokenizer (added in the first commit since the python tokenizers don't really appear to fit the use-case).
The default (and paramstyle value) is still pyformat.
> Query parameters

- impala/_rpc/hiveserver2.py
Fixes issue where database_exists and table_exists functions work only with lowercase names.
> *_exists functions ignore case

- impala/beeswax.py
- impala/dbapi.py
- impala/hiveserver2.py
Socket has no timeout now by default.
Fixes #128.
> [IMPYLA-128] Eliminate default socket timeout

- impala/beeswax.py
- impala/hiveserver2.py
If the operation isn't closed, the server will cancel the operation
which could abort a DDL op.
> Call close_operation() during cursor.close()

- impala/hiveserver2.py
When fetching the complex types data, this method will raise KeyError Exception.
```python
tcols = [_TTypeId_to_TColumnValue_getters[schema[i][1]](col)
for (i, col) in enumerate(resp.results.columns)]
```
> fix keyerror when fetching complex types data

- impala/hiveserver2.py
Analogically to https://github.com/cloudera/impyla/pull/162
It's preferable to get string representation of DATE type rather than KeyError.
> Fix KeyError when fetching DATE type.

- impala/hiveserver2.py
This will fix #157, but as noted in the ticket the two methods I was trying to call fail regardless of whether the query is being executed async or not.
> Pass async arg so that we're actually async

- impala/hiveserver2.py
The current docstring for execute_async indicates "A call to `fetch*` will
block."; this was not the case, it only appeared to do so because no execution
was ever synchronous. 1253050 fixes the lack of asynchronicity, revealing the
bug.
> Wait until execution has finished when calling cursor.fetch*

- README.md
- jenkins/run-dbapi.sh
- setup.py
Should close #173. Will merge and make release when I get a passing Jenkins build.
> Update to require thriftpy>=0.3.5, bump version to 0.13.2

- setup.py
successfully conda built impyla and ibis-framework without sasl, thrift_sasl dependencies after this change.
> remove sasl and thrift_sasl from requirments

- impala/sqlalchemy.py
Removed default execution of `select version()`, this causes a failure in Hive as the `version()` function does not exist in Hive.
I have tested and verified that this change fixes SQLAlchemy connection for Hive.
> Fix SQLAlchemy connector to work with Hive

- impala/hiveserver2.py
- impala/tests/test_hive_dict_cursor.py
For those migrated from a data platform that uses dict cursor to iterate data set :)
> Dict cursor support

- impala/interface.py
- impala/tests/test_query_parameters.py
Otherwise have fun trying to insert a string that has '%s' or '?' in it.
Closes #208
> BUG: ensure replaced strings are not included in subsequent find/replaces

- impala/hiveserver2.py
Allow the usage of the errorMessage field from the GetOperationStatus command in an exception on impala 2.7+ where IMPALA-1633 has been implemented. This will fix issue #200.
Below commit would provide this functionality for existing impala versions but has the side effect of  invalidating the query handle and breaking subsequent calls to get_log which users may rely on for extra information after a query failure.
https://github.com/schaffino/impyla/commit/cea034545611127945114e8d57d1bc122e8db1ba
> Return detailed Error Messages from query failures

- impala/_thrift_api.py
- impala/hiveserver2.py
- impala/thrift/TCLIService.thrift
Right now if you connect with impyla to Hive and issue the ``get_log()`` method on a cursor, you get:
> thriftpy.thrift.TApplicationException: Invalid method name: 'GetLog'
This is due to the fact that Hive uses another API for the retrieval of logs as answered in this [stackoverflow question](http://stackoverflow.com/questions/32530086/how-realtime-capture-logs-of-query-from-hiveserver2-with-python-client). 
This PR solves the issue by implementing and calling the necessary Hive log API when you run ``get_log()`` and solves the issues #160 and #161 as well as the remaining bits of #200 (scroll down).
> Logging function get_log() works for Hive

- impala/hiveserver2.py
Apparantly closing HiveServer2 connections doesn't solve the problem of hanging connections, since Hive session is created for every cursor. Auto-closing cursors is also necessary. This change makes `cursor.close()` operation idempotent and makes it called on delete.
> Autoclose HiveServer2 sessions

- impala/hiveserver2.py
Relating to issue #221 
* Enable usage of convert_types outside of fetchcolumnar function.
* Add fetchcbatch function so that you can work on columnar data without pulling the full result set.
* pop(0) calls were a significant cause of slowdown in the materialisng rows from the cBatch object. These have been swapped for index based access and i'm seeing up large performance increases, especially for large or wide tables.
Additionally fixed some commenting issues.
> Usability and speed improvements for fetching results

- impala/hiveserver2.py
*   Previous changes for #221 introduced a bug with NULLS when using hive due too NULL bitarray having more values than rows to be fetched and using negative indexing. Changed to index from front to avoid the issue.
*   Close in __del__ for cursor was outputting error messages in some situations where a query handle had been invalidated. Converted to best effort, ignoring any exceptions. Not sure if having a __del__ method is advisable recommend, though it is a good fallback. Explicit closing should be done as necessary. We could add context manager functionality to the cursor for easier use.
* When operation handles are invalid (timeouts, query killed through UI), session would not get closed due to thrown exception.
> BUG: Fix nulls bug introduced in #221

- setup.py
[thrift 0.10.0](https://pypi.python.org/pypi/thrift/0.10.0) package has a breaking change, closes https://github.com/cloudera/impyla/issues/235.
Currently installing `impyla` will require user to manually downgrade thrift to 0.9.3. This PR prohibits thrift 0.10.0 from being installed.
> Pin Python thrift at <= 0.9.3

- README.md
- setup.py
thrift_sasl was updated and now throws an error:
`AttributeError: 'TSSLSocket' object has no attribute 'isOpen'`
Pinning is a short term fix until the issue #268 is formally resolved.
> Pinned thrift_sasl to 0.2.1 until #268 is resolved

- impala/hiveserver2.py
- impala/interface.py
I would like to add `lastrowid` to HiveServer2Cursor to make it PEP249 compliant, and to improve compatibility with SQLAlchemy (#141).
>  If the operation does not set a rowid or if the database does not support rowids, this attribute should be set to None. (https://www.python.org/dev/peps/pep-0249/#lastrowid)
> feat: add lastrowid to HiveServer2Cursor (PEP249)

- README.md
- setup.py
Hi all,
Can we bump the version for Python 2? We're using Thrift 0.11 and having some issues with the different versions thrift. Also we can use the thrift library for Python 3: https://issues.apache.org/jira/browse/THRIFT-2096
Cheers, Fokko
> Bump Thrift for Python 2.7

- impala/hiveserver2.py
This patch fixes #256, an issue causing `KeyError` when a result column has `NULL_TYPE`.
Based on https://github.com/cloudera/impyla/blob/94a8eff9cda0cdb16b180c7079961449c8385997/impala/thrift/TCLIService.thrift#L375, it looks like Hive's `NULL_TYPE` gets mapped to TStringColumn, so I added an entry to fetch `stringVal` attribute from the column. I believe this is the rationale for a similar change in #162 to avoid `KeyError` for complex types (which also map to `stringVal`).
> Add 'NULL' to _TTypeId_to_TColumnValue_getters (fixes #256)

- impala/hiveserver2.py
- impala/tests/test_dbapi_connect.py
- impala/tests/util.py
A potential fix for #326 along with a test that demonstrates the problem.  
`SocketTracker`, the class that keeps track of opened/closed sockets for the duration of the test seems hacky, but I can't think of a better way to do this.
> issue-326 - potential fix for a socket leak in HiveServer2Cursor

- impala/_thrift_api.py
- impala/hiveserver2.py
- impala/sqlalchemy.py
A couple bug fixes.
* Fig bug in sqlalchemy parsing of username in connection string. sqlalchemy passes `username` but `connect` take `user`. ie
```
from sqlalchemy import create_engine
con_string = 'impala://<username>:<password>@hostname:port/database'
engine = create_engine(con_string)
```
* Fix bug in `_thrift_api.get_transport`. SASL doesn't recognize `LDAP` mechanism. If `auth_mechanism = 'LDAP'`, change to `'PLAIN'` after username and password checking.
> BUG: sqlalchemy connection string parsing and ldap auth

- impala/dbapi.py
- impala/hiveserver2.py
If host is registered under a different name in kerberos, we need to differentiate these two names (much like in pyhs2).
> add support for optional krb_host parameter in connection

- impala/_thrift_api.py
- jenkins/run-dbapi.sh
- setup.py
This patch addresses both #329 and #326.
Tested by setting up two different virtualenvs, and confimring that
the expected requirements were installed, and that the connect function
could be imported from impala.dbapi.
**Python 2**
```
[dknupp@mbp ~/Documents/code]$ virtualenv /tmp/python2_venv
New python executable in /tmp/python2_venv/bin/python
Installing setuptools, pip, wheel...
done.
[dknupp@mbp ~/Documents/code]$ source /tmp/python2_venv/bin/activate
(python2_venv) [dknupp@mbp ~/Documents/code]$ python --version
Python 2.7.10
(python2_venv) [dknupp@mbp ~/Documents/code]$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for …
```
> Selectively install thriftpy2 requirement based on python version

- CHANGELOG.md
- MANIFEST.in
It doesn't appear that impyla has ever included a change log in the manifest.
Since there have been so many changes, and also many requests about which
issues are getting fixed, it seems like a good time to amend that.
Based on some discussions I've had with a few on this projects, it also
feels like it might be a good time to bump the minor version to 15. In order
to avoid the types of problems we had before with regard to releasing
0.14.2, I'm also proposing that we adopt a pre-release version string at
the outset, although I'm not sure whether an alpha release (i.e., 0.15a1)
or an "rc" release (i.e., 0.15rc1) makes the most sense. In either case,
the package should only install if a user specifically requests the version.
Bare "pip install impyla" should still grab the current official …
> Add a changelog of recent commits before cutting the next release.

- impala/hiveserver2.py
- impala/interface.py
- impala/tests/test_query_parameters.py
1) For direct use of `numbe`r paramstyle fixed by making the substitution operation from a loop to a one shot regex substitution.
2) For qmark or format paramstyle: After the substition already happens successfully but gets processed again at the numeric paramstyle step. 
Fixed (workaround) by allowing the user to explicitly define the paramstyle he is using.
Bug 2) could be improved by sniffing the paramstyle or sticking with the default one and just stick with this one instead of trying to solve everything and allowing a mix of several styles?
Please advise for running your tests. Do you use a local instance running in docker?
Usage of solution 2):
`cursor.execute("INSERT INTO test_impyla VALUES (?, ?)", ['this will not go wrong:2', 'im not going to creep in'], …
> Fixed numeric parameter substitution bug  - Fixes #317 and #349

- setup.py
Allows for happybase and impyla to co-exist in a 3.7 environment.
Update based on @ethe note on the #342 PR
> Make thriftpy2 range locked, not specific version locked.

- impala/hiveserver2.py
This change adds a new property (`@rowcounts`) to cursor object. It returns modified/impacted rows and error rows.
`modifiedRows` is relevant for both kudu and non-kudu tables. 
`errorRows` is only relevant for Kudu tables. For non-kudu tables this is defaulted to -1.
> Update hiveserver2.py with new property @rowcounts

- impala/_thrift_api.py
hi, My Python Version is  `python3.6`.
when `import hiveserver2`, then raise `ImportError: cannot import name 'THttpClient'`.
This is my solution, it worked.
> fix ImportError  'THttpClient' in python3+

- setup.py
PyPI now requires that the long description content type be specified.
(Default is reSturcturedText.)
> Set long_description_content_type to markdown in setup.py

- impala/_thrift_api.py
- impala/hiveserver2.py
- Under python 3, base64.encodestring() requires a byte sequence.
- For python 3, import THttpClient from thriftpy2.http
- Impyla uses thrift for python 2 and thriftpy2 for python 3.
These libraries provide slightly different API's for opening the
transport. For thrift, the method is called isOpen() regardless
of the transport type. For thriftpy2, THttpClient retains isOpen(),
but otherwise uses is_open().
Tested by connecting to unsecure, kerberized, and HTTP impalad's
using both python 2 and python 3.
> Make connecting over HTTP compatible with python 3.

- README.md
Document later thrift-sasl versions as supported
Add some info about how to install SASL libraries
on different distros (taken from #149).
> Improve prerequisite info about SASL

- impala/_thrift_gen/TCLIService/ttypes.py
- impala/hiveserver2.py
- impala/thrift/TCLIService.thrift
Impyla uses Hive client version V6 and doesn't work correctly
against Hive client protocol version >= V10.
The issue happens when async compilation is enabled:
1. Impyla waits for the query to get into a fetchable state.
2. Impyla checks TOperationHandle.hasResultSet before trying to
fetch the results.
The problem is that TOperationHandle.hasResultSet is not set
correctly any longer. The flag was moved to
TGetOperationStatusResp in later Hive client versions.
This fix makes sure that TGetOperationStatusResp.hasResultSet is
used instead of TOperationHandle.hasResultSet if present.
Testing:
- Manually tested against a Hive client version V10.
> Fix interoperability with Hive client version >= V10 (#396)

- impala/_thrift_api.py
> Use encodebytes instead of encodestring in Python 3.9.

- impala/tests/test_dbapi_compliance.py
- impala/tests/test_dbapi_connect.py
- impala/tests/util.py
Just skip these test for now instead of fixing them.
Also remove the skips for some hive tests that blamed
HIVE-11723 - that is long fixed.
Also adds IMPYLA_SKIP_HIVE_TESTS env var to skip
the other failing test that depends on hive.
>     Disable failing tests - #401

- impala/_thrift_api.py
- impala/error.py
- impala/hiveserver2.py
- impala/tests/test_http_connect.py
Before this change Impyla is not checking HTTP return codes when
using the hs2-http protocol. Impyla is sending a request message
(e.g. send_CloseOperation) but the HTTP call to send this message may
fail. This will result in a failure when reading the reply (e.g. in
recv_CloseOperation) as there is no reply data to read. This will
typically result in an 'EOFError'.
Replace use of HTTPClient with ImpalaHttpClient. This code is copied
from Impala Shell. Make some small changes to enable this code to run on
Python3 as well as Python2. Http errors result in the throwing of a new
exception 'HttpError' (a subclass of RpcError) so that the http code can
be accessed directly.
This change does not contain any attempt to recover from an HTTP
failures but it does allow the failure to be detected. …
> Add HTTP code handling to THttpClient (#380)

- README.md
- impala/_thrift_api.py
This patch avoids putting thrift generated classes in the global
namespace and instead puts them all under impala.
Testing:
Ran tests with Python 3 and Python 2
> Vendor thrift classes with Python 3 #277

- README.md
- impala/_thrift_api.py
- impala/dbapi.py
- impala/hiveserver2.py
- impala/tests/test_util.py
- impala/util.py
- setup.py
The implementation adds a new dependency on 'kerberos' python module,
which is a pip-installed module distributed under Apache License Version 2.
When using impyla with GSSAPI over http, it is assumed that the client has a
preexisting kinit-cached Kerberos ticket that impyla can pass to the server
automatically without the user needing to reenter their password.
Examples:
1. Hive
from impala.dbapi import connect
conn = connect('hiveserver2.example.com', 10001,
auth_mechanism="GSSAPI",
kerberos_service_name='hive',
use_http_transport=True,
http_path='cliservice',
auth_cookie_name='hive.server2.auth')
cursor = conn.cursor()
cursor.execute("show databases")
res = cursor.fetchall()
2. Impala
from impala.dbapi import connect
conn = connect('impala-coordinator.exmple.com', 28000, …
> Implement GSSAPI authentication over http transport.

- README.md
- setup.py
- thrift package is not used with Python 3
- pin thrift version to 0.9.3 for Python 2
Tested with Python 2 and Python 3
> Fix specifying dependency on thrift package

- impala/_thrift_api.py
- impala/dbapi.py
- impala/error.py
- impala/hiveserver2.py
- impala/tests/test_dbapi_connect.py
- impala/tests/test_hs2_fault_injection.py
- impala/tests/test_http_connect.py
- impala/tests/test_impala.py
- impala/tests/util.py
Copy design from IMPALA-9466 and add client retry for hs2-http protocol.
Added retries for idempotent rpcs: OpenSession, GetResultSetMetadata,
CancelOperation, GetOperationStatus, GetRuntimeProfile, GetExecSummary,
and GetLog. Not done were PingImpalaHS2Service (not available) and
CloseImpalaOperation (as we cannot distinguish the non-dml statements
which are idempotent) Ported test_hs2_fault_injection.py from Impala
shell.
Add http_headers to HttpError and sleep if the 'Retry-After' header
contains an integer value.
Allow override of the http_port by setting IMPYLA_TEST_HTTP_PORT
All tests ran clean with Python2 and Python3.
> Implement simple retry which throws the underlying HttpError if retrying fails

- impala/_thrift_api.py
The docstring for connect() method in impala.dbapi module states:
ca_cert : str, optional
Local path to the the third-party CA certificate. If SSL is enabled
but the certificate is not specified, the server certificate will
not be validated.
However, the current behavior is different: if SSL is enabled,
'ca_cert' is set to None and HTTP transport is used, impyla will still
check the server certificate and reject it if it is invalid (or
self-signed).
This behavior is incorrect and not in line with impala-shell.
Testing:
- All tests ran clean with Python2 and Python3.
- Manually tested against impala coordinator with self-signed server
certificate.
> Server certs should not be verified if SSL is enabled and ca_cert is not specified

- impala/_thrift_gen/TCLIService/ttypes.py
- impala/thrift/TCLIService.thrift
The "fetchType" attribute was removed from an earlier commit. There
is code that is still reference the fetchType in hiveserver2.py. The
code was in an exception so it was most likely never hit. However, it
is needed for any HS2 api that has not implemented the deprecated
GetLog API call.
> Added "fetchType" to TFetchResultsReq.

- impala/thrift/process_thrift.sh
impala/thrift/process_thrift.sh needs an Impala checkout to run, and
some of the directory locations needed to be updated to run with a
current Impala build.
> Fix Thrift compilation with current Impala

- impala/_thrift_api.py
This can lead to ~6x speed up when fetching a large amount of data.
For details see:
https://github.com/apache/impala/commit/f672c315bc4d08d56cc7399b86767d30c9676287
> Add buffering to hs2-http

- README.md
- impala/_thrift_api.py
- impala/hiveserver2.py
- impala/tests/test_hs2_fault_injection.py
- jenkins/run-dbapi.sh
- setup.py
Apache Thrift supports Python 3 since 0.10.0 so switching to 0.11.0
allowed to use the same implementation for both Python versions.
Before this commit thriftpy2 was used with Python 3. Now thriftpy2
and the hacks to hide the differences between the two Thrift libraries
are removed.
> Unify Python 2 and 3 thrift handling and remove thriftpy2

- impala/compat.py
- impala/hiveserver2.py
- impala/tests/test_hs2_fault_injection.py
- impala/tests/test_impala.py
Optimized the code that transposes columnar batches to rows, now it
takes similar time as the related logic in impala-shell.
Benchmarked with "select * from tpch_parquet.lineitem limit 100000"
(convert_types=False, batches of 1024):
Python 2: 1.38 sec -> 0.89 sec
Python 3: 1.25 sec -> 0.76 sec
Testing:
- Ran the tests with Python 2 and 3, ImpalaDBAPI20Test gives fair
coverage to the modified functions.
- Also tested row based batches by using HIVE_CLI_SERVICE_PROTOCOL_V5.
There were no new broken tests besides the ones that already fail.
> Speed up fetchmany() and fetchall()

- impala/hiveserver2.py
This can lead to much better performance if the network has delay
and result spooling is enabled on Impala side. 10240 was chosen
because impala-shell uses the same value by default.
Note that this doesn't affect "arraysize", which is the number of
rows returned by fetchmany() by default.
> Bump fetch size to 10240 (from 1024)

- setup.py
thrift-sasl dependency was installed only with kerberos support.
This is incorrect as thrift-sasl is needed for ldap/plain authentication
as well.
> Update setup.py: thrift-sasl is needed for ldap/plain authentication

- impala/_thrift_gen/TCLIService/ttypes.py
- impala/hiveserver2.py
- impala/tests/test_data_types.py
- impala/thrift/TCLIService.thrift
The Thrift lib used with Python 3 was changed from thriftpy2 to
Apache Thrift in https://github.com/cloudera/impyla/pull/439
which broke the handling of STRING columns that contain values that
are not valid utf-8, as the library always throws an exception in
this case.
The hack to fix it is to change TStringColumn's underlying Thrift type
to 'binary' instead of 'string' and do the conversion in Impyla code.
Impala patches Thrift to solve the same issue in impala-shell,
see THRIFT-5303. I prefer a different solution for now for 2 reasons:
- THRIFT-5303 is only released in Thrift in 0.14.0, and bumping
from 0.11.0 to 0.14.0 needs more consideration.
- The way it solves the issue (replacing invalid chars) is good
for impala-shell where the final output is always text, but its
lossiness makes …
> Hack to fix non-valid utf-8 stings handling in Python 3

- impala/hiveserver2.py
TIMESTAMP was omitted from `_convert_strings_to_unicode`, causing `_parse_timestamp` to receive a bytes-like object for any returned column with a timestamp type.
Before:
```
2021-05-17 02:00:06,858 DEBUG sqlalchemy.pool.impl.QueuePool Created new connection <impala.hiveserver2.HiveServer2Connection object at 0x7f912df6ea50>
2021-05-17 02:00:06,859 DEBUG sqlalchemy.pool.impl.QueuePool Connection <impala.hiveserver2.HiveServer2Connection object at 0x7f912df6ea50> checked out from pool
2021-05-17 02:00:07,174 INFO sqlalchemy.engine.base.Engine SELECT type, fired_at FROM MyCompany.Zendesk.Zendesk_Webhook LIMIT 2
2021-05-17 02:00:07,175 INFO sqlalchemy.engine.base.Engine {}
2021-05-17 02:00:11,630 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
File …
```
> Fix TIMESTAMP handling regression in #445

- impala/tests/test_data_types.py
The timestamp handling regression was introduced
in #445 and fixed in #448.
> Add test for timestamp handling fix in #448

- impala/sqlalchemy.py
Specifically, 
1. Extend ImpalaDLLCompiler to prevent CONSTRAINT and NOT NULL clauses being added to CreateTable DDL and 
2. Translate all "string" types to STRING and "datetime" types to TIMESTAMP.
This prevents the `alembic_version` table DDL from containing a primary key constraint and a NOT NULL VARCHAR column that aren't supported in an Impala TEXT table.
> Extensions to SQLAlchemy ImpalaDLLCompiler to support Alembic schema migrations

- impala/hiveserver2.py
When I implementing get_log in my project found an issue.  
https://github.com/cloudera/impyla/blob/v0.17.0/impala/hiveserver2.py#L1345
_wrap_results takes three positional arguments but passing two arguments.
> Added missing expect_more_rows argument

- impala/_thrift_api.py
- impala/dbapi.py
- impala/hiveserver2.py
- impala/tests/test_dbapi_connect.py
- impala/util.py
Impala recently added support for authentication via a JWT
token in IMPALA-10489. This allows a user to authenticate
with a separate trusted authentication service, obtain
a JWT, and pass that JWT to Impala on the Authencation
Bearer HTTP header.
This implements support for connecting with auth_mechanism=JWT,
which requires a 'jwt' argument specifying the standard string
encoding for the JWT. This is passed on the Authentication Bearer
HTTP header on each message.
Fixes #462
Testing:
- Added unit tests in test_dbapi_connect.py
- Tested against a running Impala cluster with JWT authentication
> Add support for authentication via JWT token

- impala/_thrift_api.py
- impala/dbapi.py
- impala/hiveserver2.py
- impala/tests/test_util.py
- impala/util.py
Issue #415 added cookie support for GSSAPI authentication over HTTP
transport. But it retains only one cookie.
This patch extends support of cookie. It makes impyla retain more than
one cookies, support LDAP and GSSAPI/PLAIN SASL authentication.
Testing:
- Passed impyla tests/test_util.py.
- Passed impala custom cluster test LdapImpylaHttpTest with
verification of cookie auth.
- Manually tested the multiple cookies in HTTP headers with a
customized Impala server which could send and receive multiple
cookies.
- Manually tested impyla with GSSAPI authentication on a kerberos
enabled cluster and verified cookie auth working as expected.
> Add support for retaining cookies among http requests for LDAP and GSSAPI/PLAIN SASL #464

- impala/interface.py
- impala/tests/test_query_parameters.py
this diff fixes an issue where datetime is not correctly quoted as string when performing sql substitutions
> datetime not quoted as string

- impala/tests/_dbapi20_tests.py
The deprecated aliases were removed in Python 3.11 in python/cpython#28268 . `assertTrue` is present in both Python 2 and 3.
> Use assertTrue instead of failUnless for Python 3.11 compatibility.

- impala/tests/conftest.py
- impala/tests/test_data_types.py
- impala/tests/test_hive_dict_cursor.py
- impala/tests/test_http_connect.py
- impala/tests/test_impala.py
- @yield_fixture was replaced with @fixture as yield_fixture is deprecated
- "connect" was added as py.test marking
> Fix py.test warnings

- impala/hiveserver2.py
- impala/tests/test_hive.py
Before this change the first execute_async called by executemany()
removed "paramstyle" from the configuration map, leading to applying
default (==all) substitution rules for subsequent parameters.
Testing:
- added a regression test (executemany() was totally untested)
> Fix parameter substitution in execetutemany()

- impala/_thrift_api.py
- impala/dbapi.py
- impala/hiveserver2.py
- impala/tests/test_dbapi_connect.py
When using HTTP transport currently the Impyla driver hard codes the user_agent string as 'Python/ImpalaHttpClient'
This PR is for a way to configure this as a parameter from dbapi.connect :
<pre>
custom_user_agent = 'dbt/impala'
handle = impala.dbapi.connect(
host=credentials.host,
port=credentials.port,
auth_mechanism='LDAP',
use_http_transport=credentials.use_http_transport,
user=credentials.username,
password=credentials.password,
use_ssl=credentials.use_ssl,
http_path=credentials.http_path,
retries=credentials.retries,
user_agent=custom_user_agent
)
</pre>
To avoid confusion with impala_shell, the default user_agent string is changed to 'Python/ImpylaHttpClient'
Testcase:
impala/tests/test_dbapi_connect.py
After editing the warehouse parameters, run using:
pytest …
> enable a way to pass custom user_agent when using HTTP transport

- impala/tests/test_dbapi_connect.py
The test above was added in #498 and does not work with a default Impala cluster.
This is a test only change to make tests greens when using default authentication (=no authentication).
> Skip test_impala_ldap_connect_user_agent in case of DEFAULT_AUTH

- impala/sqlalchemy.py
- impala/tests/test_sqlalchemy.py
Impala has already supported this, we simply had to turn on this capability in the Impala dialect.
Testing:
- added test to insert + select via SQLAlchemy
> Enable supports_multivalues_insert in SQLAlchemy

- impala/interface.py
- impala/tests/test_query_parameters.py
I attempted to finally solve problem with multiple params substitution when one pass of substitution unexpectedly creates new markers as specified in https://github.com/cloudera/impyla/issues/349
I decided on doing single pass for all of positional/numeric paramstyles when no particular paramstyle is passed in configuration. This closely follows previous behaviour without interpreting "new markers" created by previous substitutions.
> Fixed numeric parameter substitution bug

- impala/dbapi.py
- impala/tests/conftest.py
- impala/tests/test_dbapi_connect.py
- impala/util.py
IMPALA-12149: Adds additional checks to ensure connection arguments that are applicable to username/password auth and JWT auth are not mixed together on the same call to the connect method.
These additional checks prevent confusion about which authentication method is actually used for the connection.
New tests were added to cover the new checks.
> IMPALA-12149: Adds additional checks to ensure valid connection arguments

- impala/dbapi.py
Connecting over Knox backed with multiple HiveServer2 Instances and Load-balancing enabled leads to Invalid Session Handle error.
The root cause of this issue is because Knox uses different cookies than default ones i.e impala.auth, impala.session.id, hive.server2.auth
This can easily be fixed by adding below property in connection string.
`http_cookie_names = ["KNOXSESSIONID","KNOX_BACKEND-HIVE"]`
It would be good to have them added to default list and avoid inconvenience.
> Add Knox cookies in default cookies list

- README.md
Current Usage part works well for Impala users but will fail for Hive users because of the `auth_mechanism` default value. 
This adds a comment targeted towards Hive users so they can quick start too.
> [Docs] Add comment to help Hive users quick start

- impala/sqlalchemy.py
This adds CHAR support which fixes errors in tables or views with CHAR type when using Impyla with Apache Superset.
> Support CHAR type in SQLAlchemy

- impala/tests/test_sqlalchemy.py
sqlalchemy 2 (now default on pip) removed some functions used in tests. Updated tests to work both with sqlalchemy 2.* and 1.* (>=1.2).
> Fix test_sqlalchemy with sqlalchemy 2

- impala/hiveserver2.py
- impala/tests/test_hs2_fault_injection.py
- impala/tests/test_impala.py
With current Impala server rowcount support needs DMLs to be closed with CloseImpalaOperation() as there is no simpler way to get the number of modifed rows.
See https://issues.apache.org/jira/browse/IMPALA-12647 for alternatives.
This change adds option close_finished_queries for cursors with default True. Setting it to False brings back the old behavior.
If queries are closed after finishing queries, calling get_log RPC is no longer possible. If close_finished_queries is true then the logs are fetched and stored before closing to query to be able to return the saved results with get_log. Generally get_log shouldn't be a too expensive RPC.
Another potential side-effect is that get_profile may fail as Impala can discard the runtime profile after the query is closed (see Impala flag …
> Support Cursor.rowcount and close finished queries

- impala/_thrift_api.py
- impala/tests/test_dbapi_connect.py
Python 3.12 removed deprecated certfile and key_file arguments from http_client.HTTPSConnection. These should be always empty in Impyla as the server is never verified in https connections (see #362).
> Issue #529: Fix https connection with Python 3.12

- impala/interface.py
- impala/sqlalchemy.py
I updated some minor versions of some dependencies in my own application and the following error popped up. I checked other strings that were used with the `re` module, and those were all raw strings, so I checked and if I manually (and locally) changed the string to a raw string, everything ran fine.
```
E     File "/home/david/workon/impala-39/lib/python3.9/site-packages/impala/sqlalchemy.py", line 227
E       m = re.match('.*?(\d{1,3})\.(\d{1,3})\.(\d{1,3}).*', v)
E                    ^
E   SyntaxError: invalid escape sequence \d
```
Not sure why updating dependencies broke this code specifically.
> Turn regex strings into raw strings

- impala/hiveserver2.py
This function is called for every query during normal execution, making this info level too verbose.
> Log "Closing operation" at debug level

- impala/sqlalchemy.py
1. Add text() wrapper for metadata queries.
2. Remove table names from get_column output
> Fix SQLAlchemy support for Impala on Python 3.10

- impala/_thrift_api.py
At the moment the actual password is logged at debug level. It is not good practice to log sensitive information.
> Log fake password instead of actual password to avoid leaking sensitive info

- impala/hiveserver2.py
- impala/tests/test_dbapi_connect.py
See the #549 for the detailed analyses of the issue.
The fix works similarly to the existing solution for http connections:
- each RPC knows whether it is idempotent
- if the error comes from establishing the connection, then retry
- if the error comes from executing the RPC, only retry if the RPC is idempotent
A test is added that relies on slow metadata handling in the Impala cluster to trigger timouts. It would be nice to add wider and more reliable tests in the future similarly to the http tests in test_hs2_fault_injection.py
> Avoid retrying non-idempotent RPCs in binary connections (#549)

- impala/hiveserver2.py
- impala/tests/conftest.py
- impala/tests/test_data_types.py
https://github.com/cloudera/impyla/issues/543
> Allow skipping utf8 converison in Python3

- impala/_thrift_api.py
The issue was introduced in #542.
Caught by Impala's LdapImpylaHttpTest.
> Always set ImpalaHttpClient.__preserve_all_cookies

- setup.py
bitarray 3.0 removed Python 2.7 support, which led to failing to build sdist for Python 2.7. Besides Python 2.7 support several function were removed in 3.0, so it seems safer to use 2.* at the moment. Impala pins the dependency to 2.3 - I preferred to be more flexible in Impyla.
> Restrict bitarray varsion to 2.*

- README.md
- impala/_thrift_api.py
- impala/dbapi.py
- impala/hiveserver2.py
- impala/tests/test_hs2_fault_injection.py
- impala/tests/test_http_connect.py
In a modern Impala deployment hs2-http protocol is used in a system where http messages pass through one or more http proxies. Some of these proxies add their own http message headers to messages as they are forwarded. It would be useful to test Impala with some of the message headers that are added by http proxies. In particular the case where there are multiple http headers with the same name is hard to simulate with clients such as Impyla or Impala Shell. This is partly because these clients store http headers in a Python dict which does not allow duplicate keys.
Extend the Impyla connect() method to add
a 'get_user_custom_headers_func' parameter. This specifies a function that is called as http message headers are being written. The function should return a list of tuples, each tuple …
> Allow users to add custom http headers when using hs2-http (#557)

- impala/_thrift_api.py
- impala/tests/test_http_connect.py
- impala/tests/test_thrift_api.py
- impala/tests/test_util.py
- impala/util.py
- Added tests that cover the descriptions of #540 and #517 
- Changed plain/ldap auth and proxy authentication to use the same utility function to encode credentials
Fixes #540
Fixes #517 
Note:
1. Tested with 2.7 and 3.7+
2. Tried to use module-local conventions (e.g. unittest/pytest)
3. I'm using impala quickstarter (4.4.1) for local test execution, no hive tests executed
4. `impala.tests.test_dbapi_connect.ImpalaConnectionTests.test_retry_dml` generally fails for me (and failed also before making any modifcations)
> Fix proxy-authentication headers for Python 3.* and long basic credential encodings

- impala/sqlalchemy.py
- impala/tests/test_sqlalchemy.py
- tox.ini
Fixes #567 
Added arbitrary keyword arguments to `has_table()`.
This lets `has_table()` accept  `'info_cache'` (and other unknown kwargs that may be passed by SQLAlchemy to the dialect's `has_table()` in the future).
> df.to_sql() support for impala + SQLAlchemy: has_table() got an unexpected argument 'info_cache'

- impala/_thrift_api.py
- impala/tests/test_hs2_fault_injection.py
- impala/tests/test_http_connect.py
- impala/tests/test_sqlalchemy.py
- impala/tests/util.py
- add brackets to ipv6 addresses in urls (e.g. https://[::1]:28000)
- fix tests to work with IMPYLA_TEST_HOST=::1
Tested with WIP patch for IPv6 support in Impala:
https://gerrit.cloudera.org/#/c/22527/
> Fix IPv6 address handling in hs2-http2 (#570)

- setup.py
Python 2.7 needs bitarray < 3, but on Python bitarray 3.* can be used. The bitarray functionality used in impyla is minimal and didn't change with the major version bump.
> Unpin bitarray dependency on Python 3

- impala/sqlalchemy.py
This fixes the following warning:
ADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().
The issue was mentioned in #214
> Add import_dbapi() class method to ImpalaDialect

- CHANGELOG.md
- impala/__init__.py
- setup.py
Also removed Python 3.6 (EOL since 2021) from the supported versions. It is still likely to work but testing it is a nuisance.
> Prepare release 0.22a1
